<?php

namespace App\Command;

use App\Entity\PayoutRequest;
use App\Repository\DesignerEarningsRepository;
use App\Repository\PayoutRequestRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;

#[AsCommand(
    name: 'app:process-artist-payouts',
    description: 'Automatically process artist payouts for earnings above minimum threshold',
)]
class ProcessArtistPayoutsCommand extends Command
{
    private const MINIMUM_PAYOUT_AMOUNT = '10.00'; // $10 minimum
    private const DEFAULT_CURRENCY = 'USD';

    public function __construct(
        private readonly UserRepository $userRepository,
        private readonly DesignerEarningsRepository $earningsRepository,
        private readonly PayoutRequestRepository $payoutRequestRepository,
        private readonly EntityManagerInterface $entityManager
    ) {
        parent::__construct();
    }

    protected function configure(): void
    {
        $this->addOption(
            'dry-run',
            null,
            InputOption::VALUE_NONE,
            'Show what would be processed without actually creating payout requests'
        );
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);
        $dryRun = $input->getOption('dry-run');

        $io->title('Processing Artist Payouts');

        if ($dryRun) {
            $io->note('DRY RUN MODE - No payout requests will be created');
        }

        // Find all artists
        $artists = $this->userRepository->createQueryBuilder('u')
            ->where('u.isArtist = :isArtist')
            ->setParameter('isArtist', true)
            ->getQuery()
            ->getResult();

        if (empty($artists)) {
            $io->info('No artists found.');

            return Command::SUCCESS;
        }

        $io->progressStart(count($artists));
        $processed = 0;
        $skipped = 0;
        $errors = 0;

        foreach ($artists as $artist) {
            try {
                // Get total earnings
                $totalEarnings = $this->earningsRepository->getTotalEarnings($artist);

                // Get total pending payout requests
                $pendingPayouts = $this->payoutRequestRepository->getTotalPendingAmount($artist);

                // Calculate available balance
                $availableBalance = bcsub($totalEarnings, $pendingPayouts, 2);

                // Check if balance meets minimum threshold
                if (bccomp($availableBalance, self::MINIMUM_PAYOUT_AMOUNT, 2) < 0) {
                    $io->progressAdvance();
                    ++$skipped;
                    continue;
                }

                // Check if there's already a pending payout request
                $existingPending = $this->payoutRequestRepository->findPendingByDesigner($artist);
                if (!empty($existingPending)) {
                    $io->writeln(sprintf(
                        '  ⚠️  %s already has a pending payout request (skipping)',
                        $artist->getUsername()
                    ));
                    $io->progressAdvance();
                    ++$skipped;
                    continue;
                }

                // Create automated payout request
                if (!$dryRun) {
                    $payoutRequest = new PayoutRequest();
                    $payoutRequest->setDesigner($artist);
                    $payoutRequest->setAmount($availableBalance);
                    $payoutRequest->setCurrency(self::DEFAULT_CURRENCY);
                    $payoutRequest->setStatus(PayoutRequest::STATUS_PENDING);
                    $payoutRequest->setIsAutomated(true);
                    $payoutRequest->setAdminNotes('Automated payout request generated by cron job');

                    $this->entityManager->persist($payoutRequest);
                    $this->entityManager->flush();
                }

                $io->writeln(sprintf(
                    '  ✓ Created payout request for %s: $%s',
                    $artist->getUsername(),
                    $availableBalance
                ));

                ++$processed;
            } catch (\Exception $e) {
                $io->error(sprintf(
                    '  ✗ Error processing %s: %s',
                    $artist->getUsername(),
                    $e->getMessage()
                ));
                ++$errors;
            }

            $io->progressAdvance();
        }

        $io->progressFinish();

        $io->success(sprintf(
            'Completed! Processed: %d, Skipped: %d, Errors: %d',
            $processed,
            $skipped,
            $errors
        ));

        return Command::SUCCESS;
    }
}
